[package]
name = "rust"
version = "0.1.0"
authors = ["Johnny Bergström <github@joonix.se>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wee_alloc = { version = "0.4.2", optional = true }
